name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - "Build and Push Docker Image to Amazon ECR"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 771088247647.dkr.ecr.ap-south-1.amazonaws.com

            sudo docker pull 771088247647.dkr.ecr.ap-south-1.amazonaws.com/medical-chatbot:latest

            sudo docker stop medical-chatbot || true

            sudo docker rm medical-chatbot || true

            sudo docker run -d \
              --name medical-chatbot \
              --restart unless-stopped \
              -p 8501:8501 \
              771088247647.dkr.ecr.ap-south-1.amazonaws.com/medical-chatbot:latest